// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Bookshelf;

{ITE} {DFMFileType} {InsertWindow.dfm}
{ITE} {DFMFileType} {MainWindow.dfm}
{ITE} {DFMFileType} {TransferWindow.dfm}
{ITE} {RCFileType} {Bookshelf_DRC.rc}

{$R 'InsertWindow.dfm' 'InsertBookForm:TForm'}
{$R 'MainWindow.dfm' 'MainWindowForm:TForm'}
{$R 'TransferWindow.dfm' 'TransferForm:TForm'}
{$R 'Bookshelf_DRC.res' 'Bookshelf_DRC.rc'}

{$E HRV}

begin
end.
